#!/bin/bash
# My first script

echo "Running many clustering tests..."
python3 stacker.py RFs_Yellowstone_280_800_jgf1_prem_1.PICKLE 'prem' 280 780
python3 stacker.py RFs_Yellowstone_280_800_jgf1_SL2014_1.PICKLE 'default' 280 780
python3 stacker.py RFs_Yellowstone_280_800_jgf1_SL2014_1.PICKLE 'shallow' 280 580
python3 stacker.py RFs_Yellowstone_280_800_jgf1_SL2014_1.PICKLE 'deep' 480 780

